---
- name: Update and upgrade (Debian, Ubuntu)
  apt:
    upgrade: dist
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Update and upgrade (Centos)
  yum:
    name: '*'
    state: latest
    autoremove: yes
  when: ansible_distribution == "CentOS"
