---
- name: Enable cron (Ubuntu)
  service:
    name: cron
    enabled: yes
    
- name: Password expiration
  lineinfile:
    dest: /etc/apt/apt.conf.d/10periodic
    regexp: "^APT::Periodic::Update-Package-Lists"
    line: APT::Periodic::Update-Package-Lists "1";

- name: Disable guest account
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    line: allow-guest=false
    create: yes

- name: Disable greet user #run service lightdm restart for these to take effect
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    line: greeter-show-remote-login=false
    create: yes
