---
- name: Basic best practices, settings
  hosts: localhost

  tasks:
  - { include: password-policy.yml, become: yes}
  - { include: file-permissions.yml, become: yes}
  - { include: random-checks.yml, become: yes}