#https://linuxhint.com/secure_password_policies_ubuntu/
---
- name: Password expiration
  lineinfile:
    path: /etc/login.defs
    regex: "^PASS_MAX_DAYS"
    line: PASS_MAX_DAYS 90

- name: Password expiration
  lineinfile:
    path: /etc/login.defs
    regex: "^PASS_WARN_AGE"
    line: PASS_WARN_AGE 7

- name: Password expiration
  lineinfile:
    path: /etc/login.defs
    regex: "^PASS_MAX_DAYS"
    line: PASS_MAX_DAYS 90

- name: Install cracklib pkg
  package: name=libpam-cracklib state=present

- name: Password creation requirement
  lineinfile:
    path: /etc/pam.d/common-password
    regex: "^pam_cracklib.so"
    line: password  requisite   pam_cracklib.so retry=3 minlen=8 difok=3ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-

- name: Password creation requirement
  lineinfile:
    path: /etc/pam.d/common-auth
    regex: "^pam_unix.so"
    line: auth [success=1 default=ignore]  pam_unix.so nullok_secure remember=5 minlen=8