---
- name: Enable cron (Ubuntu)
  service:
    name: cron
    enabled: yes
    
- name: Update package lists
  lineinfile:
    dest: /etc/apt/apt.conf.d/10periodic
    regexp: "^APT::Periodic::Update-Package-Lists"
    line: APT::Periodic::Update-Package-Lists "1";
