---
- name: Shadow and gshadow file permissions
  file: 
    dest: "{{item}}"
    mode: 0640
    owner: root
    group: shadow
  with_items:
    - /etc/shadow
    - /etc/shadow-
    - /etc/gshadow
    - /etc/gshadow-

- name: Root read only directories
  file:  
    dest: "{{item}}"
    owner: root
    group: root
    mode: 0600
    state: directory
  with_items:
    - /etc/cron.d
    - /etc/cron.hourly
    - /etc/cron.daily
    - /etc/cron.weekly
    - /etc/cron.monthly

- name: Root read only file
  file: dest=/boot/grub/grub.cfg owner=root group=root mode=0600
  
- name: Root own, world read file permissions
  file: 
    dest: "{{item}}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - /etc/passwd
    - /etc/passwd-
    - /etc/group
    - /etc/group-
    - /etc/hosts.deny
    - /etc/hosts.allow
    - /etc/issue