---
- name: Ensure /etc/.anso exists
  file: 
    dest: /etc/.anso
    state: directory
    owner: root
    group: root
    mode: '0640'
    
- name: Download LinPeas
  git:
    repo: 'https://github.com/carlospolop/PEASS-ng.git'
    dest: /etc/.anso/PEASS-ng

- name: Run script and output to /etc/.anso/linenum.out
  shell: /etc/.anso/PEASS-ng/linPEAS/linpeas.sh >> /etc/.anso/linpeas.txt