---
- name: Competition hardening
  hosts: localhost
  
  roles:
  #- { role: backup-files, become: yes }
  - { role: audit, become: yes }
  - { role: linpeas, become: yes }
  - { role: logon-banners, become: yes }
  - { role: best-practices, become: yes }
  #- { role: package, become: yes }
  #- { role: sshd, become: yes }