---
- name: Remove vulnerable packages (Ubuntu)
  apt:
    pkg: 
    - socat
    - nc
    - netcat
    - nmap
    state: absent
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Remove vulnerable packages (Centos)
  yum:
    pkg: 
    - socat
    - nc
    - netcat
    - nmap
    state: absent
  become: true
  when: ansible_distribution == "Centos"    